---
fail_fast: false
default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=250
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      # disabled as there is no possibility to ignore a file
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        files: \^(?!output$).*$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.config.yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
        args:
          - --config
          - .markdownlint.yaml

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        args:
          - --ignore-path
          - .prettierignore
          - --config
          - .prettierrc.js
