---
name: build and deploy

on:
  push:
    branches:
      - main
    paths:
      - satis.json
  schedule:
    - cron: 30 6 * * 1

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@v1.11.0
        with:
          app-id: ${{ secrets.STRG_SATIS_GITHUB_APP_ID }}
          private-key: ${{ secrets.STRG_SATIS_GITHUB_PEM }}
          owner: ${{ github.repository_owner }}

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - name: satis build
        uses: tyriis/satis-build@c73209ab6b0b46440a31f6b5776e122fa650a463 # v1.6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/multi-file-commit
      - name: multi-file-commit
        id: multi-file-commit
        uses: tyriis/multi-file-commit@v0.3.14
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: main
          message: "chore: satis build"

  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # https://github.com/marketplace/actions/configure-github-pages
      - name: setup pages
        uses: actions/configure-pages@v5.0.0

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Upload entire repository
          path: "."

      # https://github.com/marketplace/actions/deploy-github-pages-site
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
