---
name: build and deploy

on:
  push:
    branches:
      - main
    paths:
      - satis.json
  schedule:
    - cron: 30 6 * * 1

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/create-github-app-token
      - name: generate token
        id: generate-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ secrets.STRG_SATIS_GITHUB_APP_ID }}
          private-key: ${{ secrets.STRG_SATIS_GITHUB_PEM }}
          owner: ${{ github.repository_owner }}

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - name: satis build
        uses: tyriis/satis-build@c73209ab6b0b46440a31f6b5776e122fa650a463 # v1.6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      # https://github.com/marketplace/actions/multi-file-commit
      - name: multi-file-commit
        id: multi-file-commit
        uses: tyriis/multi-file-commit@923a5965f42ba24546ff393c12aa3203b8b3855b # v0.3.14
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: main
          message: "chore: satis build"

  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/configure-github-pages
      - name: setup pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          # Upload entire repository
          path: "."

      # https://github.com/marketplace/actions/deploy-github-pages-site
      - name: deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
