---
# Schedule composer build

name: satis build

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/github-app-token
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - uses: dev-this/satis-build@v1
        with:
          token: "${{ steps.generate-token.outputs.token }}"

      - name: GIT Commit Changes
        run: "git add . && git commit -m 'chore: satis build'"

      - name: GIT Push Changes
        run: git push
