---
# Schedule composer build

name: satis-build

on:
  schedule:
    - cron: "30 6 * * 1"
  push:
    branches:
      - main
    paths:
      - "satis.json"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/oleksiyrudenko/gha-git-credentials
      - name: Setup GIT
        uses: oleksiyrudenko/gha-git-credentials@e7a10d8587d4d9706f13965a1442e329f5be53d7 # v2.1
        with:
          token: ${{ secrets.GH_PUSH }}
          email: ${{ secrets.STRG_AUTOMATION_USER_EMAIL }}
          name: STRG Automation

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - uses: tyriis/satis-build@c73209ab6b0b46440a31f6b5776e122fa650a463 # v1.6
        with:
          token: ${{ secrets.GH_PUSH }}

      - name: GIT Commit Changes
        run: "git add . && git commit -m 'chore: satis build'"

      - name: GIT Push Changes
        run: git push
