---
# Schedule composer test

name: satis-test

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - uses: tyriis/satis-build@c73209ab6b0b46440a31f6b5776e122fa650a463 # v1.6
        with:
          token: ${{ secrets.GH_PUSH }}
