---
# Schedule composer build

name: satis-build

on:
  schedule:
    - cron: "30 6 * * 1"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      # https://github.com/oleksiyrudenko/gha-git-credentials
      - name: Setup GIT
        uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: ${{ secrets.GH_PUSH }}
          email: ${{ secrets.STRG_AUTOMATION_USER_EMAIL }}
          name: STRG Automation

      # https://github.com/marketplace/actions/satis-build-composer-repository
      - uses: tyriis/satis-build@v1.6
        with:
          token: ${{ secrets.GH_PUSH }}

      - name: GIT Commit Changes
        run: "git add . && git commit -m 'chore: satis build'"

      - name: GIT Push Changes
        run: git push
